/* MARKERS */
export const MARKERS_LOAD_SUCCESS = 'MARKERS_LOAD_SUCCESS';
export const MARKER_SHOW_INFOBOX = 'MARKER_SHOW_INFOBOX';
export const MARKER_HIDE_INFOBOXES = 'MARKER_HIDE_INFOBOXES';
export const MARKERS_ADD_TO_MAP = 'MARKERS_ADD_TO_MAP';
export const MARKERS_HIDE_FROM_MAP = 'MARKERS_HIDE_FROM_MAP';
export const MARKERS_UPDATE_FOR_USERNAME = 'MARKERS_UPDATE_FOR_USERNAME';

/* DIRECTIONS */
export const DIRECTION_BUILD = 'DIRECTION_BUILD';
export const DIRECTIONS_CLEAR = 'DIRECTIONS_CLEAR';

/* USERS */
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USER_ACTIVE_SIGNUP = 'USER_ACTIVE_SIGNUP';
export const USER_ACTIVE_LOGIN = 'USER_ACTIVE_LOGIN';
export const USER_ACTIVE_LOADED = 'USER_ACTIVE_LOADED';
export const USER_ACTIVE_LOGOUT = 'USER_ACTIVE_LOGOUT';

export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
