/* MARKERS */
export const MARKERS_LOAD_SUCCESS = 'MARKERS_LOAD_SUCCESS';
export const MARKER_SHOW_INFOBOX = 'MARKER_SHOW_INFOBOX';
export const MARKER_HIDE_INFOBOXES = 'MARKER_HIDE_INFOBOXES';
export const MARKERS_ADD_TO_MAP = 'MARKERS_ADD_TO_MAP';
export const MARKERS_HIDE_FROM_MAP = 'MARKERS_HIDE_FROM_MAP';
export const MARKERS_UPDATE_FOR_USERNAME = 'MARKERS_UPDATE_FOR_USERNAME';

/* DIRECTIONS */
export const DIRECTION_BUILD = 'DIRECTION_BUILD';
export const DIRECTIONS_CLEAR = 'DIRECTIONS_CLEAR';

/* USERS */
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USER_ACTIVE_LOADED = 'USER_ACTIVE_LOADED';

/* CONNECTIONS */
export const CONNECTIONS_LOAD_SUCCESS = 'CONNECTIONS_LOAD_SUCCESS';
export const CONNECTIONS_ADD_NEW = 'CONNECTIONS_ADD_NEW';
export const CONNECTIONS_DELETE_ONE = 'CONNECTIONS_DELETE_ONE';

export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
