/* MARKERS */
export const MARKERS_LOAD_SUCCESS = 'MARKERS_LOAD_SUCCESS';
export const MARKER_SHOW_INFOBOX = 'MARKER_SHOW_INFOBOX';
export const MARKER_HIDE_INFOBOXES = 'MARKER_HIDE_INFOBOXES';
export const MARKERS_FILTER = 'MARKERS_FILTER';

/* DIRECTIONS */
export const DIRECTION_BUILD = 'DIRECTION_BUILD';
export const DIRECTIONS_CLEAR = 'DIRECTIONS_CLEAR';
