/* MARKERS */
export const LOAD_MARKERS_SUCCESS = 'LOAD_MARKERS_SUCCESS';
export const SHOW_MARKER_INFOBOX = 'SHOW_MARKER_INFOBOX';

/* DIRECTIONS */
export const BUILD_DIRECTION = 'BUILD_DIRECTION';
