/* MARKERS */
export const MARKERS_LOAD_SUCCESS = 'MARKERS_LOAD_SUCCESS';
export const MARKER_SHOW_INFOBOX = 'MARKER_SHOW_INFOBOX';
export const MARKER_HIDE_INFOBOXES = 'MARKER_HIDE_INFOBOXES';
export const MARKERS_ADD_TO_MAP = 'MARKERS_ADD_TO_MAP';
export const MARKERS_HIDE_FROM_MAP = 'MARKERS_HIDE_FROM_MAP';

/* DIRECTIONS */
export const DIRECTION_BUILD = 'DIRECTION_BUILD';
export const DIRECTIONS_CLEAR = 'DIRECTIONS_CLEAR';

/* DIRECTIONS */
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
